name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ".dotfiles"
    - name: Check that we can install the dotfiles
      run: |
        ~/.dotfiles/install
